### ISSUE TITLE
Source & binaries

### ISSUE THREAD

**Issue by mikessh** [infspiredBAT/ARResT.Interrogate#1]
Dear ARResT team,

I'm very eager to test the software, however it says that the code will be here upon publication, which apparently happened this October (http://bioinformatics.oxfordjournals.org/content/early/2016/10/11/bioinformatics.btw634). Can you please elaborate on when the code and binaries will be available.

Best regards,
Mike

**Comment by nikosdarzentas** [comment]
Hello Mike,

Thanks for your message, and interest. Sometimes the timing of things is not great, i.e. we were in the middle of a lot of dev work and we wanted to feel confident with the release and give everyone a solid common starting point - not ideal in many ways, but that's the choice we made.
 
Anyway, we just released 'ARResT/Interrogate' in a new repo called just "ARResT" - you'll find it under @infspiredBAT - and we'll eventually remove this one.

Best wishes.
